# =====================================================================================
# STREAMLIT THEME CONFIGURATION - "MISSION CONTROL"
# =====================================================================================
# This file defines a custom dark theme for the Streamlit application, inspired by
# high-tech dashboards in aerospace and data centers.
# =====================================================================================

[theme]

# A vibrant, glowing blue for interactive elements.
primaryColor = "#00A9FF"

# A deep, near-black charcoal for the main background.
backgroundColor = "#1A202C"

# A slightly lighter dark color for cards and secondary areas.
secondaryBackgroundColor = "#2C3A47"

# A light, readable grey for all primary text.
textColor = "#F0F2F6"

# The base font family. Specific fonts will be loaded via custom CSS.
font = "sans serif"
